"""add_generic_gateway_fields_to_payments

Revision ID: 99b3f79156bf
Revises: ee92ac1e10d4
Create Date: 2026-04-21 17:13:38.893866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b3f79156bf'
down_revision: Union[str, None] = 'ee92ac1e10d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('gateway_order_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('gateway_payment_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('gateway_signature', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_gateway_order_id'), 'payments', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_payments_gateway_payment_id'), 'payments', ['gateway_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_gateway_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_order_id'), table_name='payments')
    op.drop_column('payments', 'gateway_signature')
    op.drop_column('payments', 'gateway_payment_id')
    op.drop_column('payments', 'gateway_order_id')
    # ### end Alembic commands ###
