"""add_certificate_type_and_payment_requirement_to_events

Revision ID: 0d82f1241dd7
Revises: 36343d051da4
Create Date: 2026-04-21 16:39:19.499921

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d82f1241dd7"
down_revision: str | None = "36343d051da4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("certificate_type", sa.String(length=20), nullable=True))
    op.add_column("events", sa.Column("requires_payment", sa.Boolean(), nullable=True))
    op.drop_constraint("registrations_event_category_id_fkey", "registrations", type_="foreignkey")
    op.drop_constraint("registrations_event_id_fkey", "registrations", type_="foreignkey")
    op.create_foreign_key(None, "registrations", "events", ["event_id"], ["id"])
    op.create_foreign_key(None, "registrations", "event_categories", ["event_category_id"], ["id"])
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("user", "admin", "super_admin", name="userrole"),
        type_=sa.String(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'user'::userrole"),
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM("user", "admin", "super_admin", name="userrole"),
        existing_nullable=False,
        existing_server_default=sa.text("'user'::userrole"),
    )
    op.drop_constraint(None, "registrations", type_="foreignkey")
    op.drop_constraint(None, "registrations", type_="foreignkey")
    op.create_foreign_key(
        "registrations_event_id_fkey",
        "registrations",
        "events",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "registrations_event_category_id_fkey",
        "registrations",
        "event_categories",
        ["event_category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("events", "requires_payment")
    op.drop_column("events", "certificate_type")
    # ### end Alembic commands ###
