"""Add Strava integration tables

Revision ID: 36343d051da4
Revises: 004
Create Date: 2026-04-19 14:18:38.906668

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36343d051da4"
down_revision: str | None = "004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strava_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.BigInteger(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scope", sa.String(length=500), nullable=True),
        sa.Column("athlete_data", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_strava_connections_athlete_id"), "strava_connections", ["athlete_id"], unique=True
    )
    op.create_index(op.f("ix_strava_connections_id"), "strava_connections", ["id"], unique=False)
    op.create_table(
        "challenge_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("strava_connection_id", sa.Integer(), nullable=True),
        sa.Column("strava_activity_id", sa.BigInteger(), nullable=True),
        sa.Column("activity_type", sa.String(length=50), nullable=False),
        sa.Column("activity_name", sa.String(length=500), nullable=True),
        sa.Column("distance_meters", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("elevation_gain_meters", sa.Integer(), nullable=True),
        sa.Column("average_speed", sa.Integer(), nullable=True),
        sa.Column("max_speed", sa.Integer(), nullable=True),
        sa.Column("activity_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strava_connection_id"],
            ["strava_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_challenge_activities_activity_date"),
        "challenge_activities",
        ["activity_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_challenge_activities_id"), "challenge_activities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_challenge_activities_strava_activity_id"),
        "challenge_activities",
        ["strava_activity_id"],
        unique=True,
    )
    op.create_table(
        "user_challenge_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("total_distance_km", sa.Integer(), nullable=True),
        sa.Column("total_activities", sa.Integer(), nullable=True),
        sa.Column("total_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("goal_distance_km", sa.Integer(), nullable=True),
        sa.Column("progress_percentage", sa.Integer(), nullable=True),
        sa.Column("last_activity_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_streak_days", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_challenge_progress_id"), "user_challenge_progress", ["id"], unique=False
    )
    op.drop_table("event_checkpoints")
    op.drop_index("idx_sponsors_event", table_name="event_sponsors")
    op.drop_table("event_sponsors")
    op.create_index(op.f("ix_event_categories_id"), "event_categories", ["id"], unique=False)
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_index(op.f("ix_registrations_id"), "registrations", ["id"], unique=False)
    op.drop_constraint("uq_users_email", "users", type_="unique")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    op.drop_index(op.f("ix_registrations_id"), table_name="registrations")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_index(op.f("ix_event_categories_id"), table_name="event_categories")
    op.create_table(
        "event_sponsors",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("logo_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("website_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("sponsor_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "display_order",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name="event_sponsors_event_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="event_sponsors_pkey"),
    )
    op.create_index("idx_sponsors_event", "event_sponsors", ["event_id"], unique=False)
    op.create_table(
        "event_checkpoints",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("checkpoint_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "distance_from_start",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "latitude", sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True
        ),
        sa.Column(
            "longitude", sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True
        ),
        sa.Column(
            "elevation", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name="event_checkpoints_event_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="event_checkpoints_pkey"),
    )
    op.drop_index(op.f("ix_user_challenge_progress_id"), table_name="user_challenge_progress")
    op.drop_table("user_challenge_progress")
    op.drop_index(
        op.f("ix_challenge_activities_strava_activity_id"), table_name="challenge_activities"
    )
    op.drop_index(op.f("ix_challenge_activities_id"), table_name="challenge_activities")
    op.drop_index(op.f("ix_challenge_activities_activity_date"), table_name="challenge_activities")
    op.drop_table("challenge_activities")
    op.drop_index(op.f("ix_strava_connections_id"), table_name="strava_connections")
    op.drop_index(op.f("ix_strava_connections_athlete_id"), table_name="strava_connections")
    op.drop_table("strava_connections")
    # ### end Alembic commands ###
