"""add_razorpay_fields_to_payments

Revision ID: ee92ac1e10d4
Revises: 0d82f1241dd7
Create Date: 2026-04-21 16:49:02.244598

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee92ac1e10d4"
down_revision: str | None = "0d82f1241dd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("razorpay_order_id", sa.String(length=100), nullable=True))
    op.add_column(
        "payments", sa.Column("razorpay_payment_id", sa.String(length=100), nullable=True)
    )
    op.add_column("payments", sa.Column("razorpay_signature", sa.String(length=255), nullable=True))
    op.add_column("payments", sa.Column("refund_id", sa.String(length=100), nullable=True))
    op.add_column(
        "payments", sa.Column("refund_amount", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.add_column("payments", sa.Column("refund_status", sa.String(length=50), nullable=True))
    op.add_column("payments", sa.Column("refunded_at", sa.TIMESTAMP(), nullable=True))
    op.create_index(
        op.f("ix_payments_razorpay_order_id"), "payments", ["razorpay_order_id"], unique=False
    )
    op.create_index(
        op.f("ix_payments_razorpay_payment_id"), "payments", ["razorpay_payment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_razorpay_payment_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_razorpay_order_id"), table_name="payments")
    op.drop_column("payments", "refunded_at")
    op.drop_column("payments", "refund_status")
    op.drop_column("payments", "refund_amount")
    op.drop_column("payments", "refund_id")
    op.drop_column("payments", "razorpay_signature")
    op.drop_column("payments", "razorpay_payment_id")
    op.drop_column("payments", "razorpay_order_id")
    # ### end Alembic commands ###
