-- Insert sample events for GlycoGrit
-- Run this on Railway's PostgreSQL database

INSERT INTO events (
    name, slug, description, event_type, status, start_date, end_date,
    location, total_distance, max_participants, current_participants,
    registration_fee, currency, difficulty_level, goals, rewards, rules,
    is_virtual, is_featured, created_at, updated_at
) VALUES
(
    '30-Day Running Challenge',
    '30-day-running-challenge',
    'Build your running habit with our 30-day challenge. Run at least 3km every day for 30 days.',
    'running',
    'registration_open',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '30 days',
    'Virtual - Anywhere',
    90.0,
    1000,
    0,
    0.0,
    'INR',
    'beginner',
    '["Run 3km daily", "Complete 30 consecutive days", "Build a running habit"]'::jsonb,
    '["Digital certificate", "30-Day Runner badge", "Entry into prize draw"]'::jsonb,
    E'Must log at least 3km run each day\nRest days allowed with prior notification\nActivity must be verified via tracking app',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Mumbai Half Marathon Training',
    'mumbai-half-marathon-training',
    '12-week structured training program to prepare you for a half marathon (21.1km). Perfect for intermediate runners.',
    'marathon',
    'registration_open',
    CURRENT_DATE + INTERVAL '7 days',
    CURRENT_DATE + INTERVAL '91 days',
    'Mumbai, Maharashtra',
    21.1,
    500,
    0,
    1500.0,
    'INR',
    'intermediate',
    '["Complete 21.1km race", "Improve endurance", "Follow structured training plan"]'::jsonb,
    '["Race entry included", "Training plan access", "Finisher medal"]'::jsonb,
    E'Must complete weekly long runs\nFollow the provided training schedule\nParticipate in group runs (optional)',
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Cycling Century Challenge',
    'cycling-century-challenge',
    'Ride 100km in a single day! Join cyclists across India in this epic one-day challenge.',
    'cycling',
    'registration_open',
    CURRENT_DATE + INTERVAL '14 days',
    CURRENT_DATE + INTERVAL '14 days',
    'Multiple cities - Virtual',
    100.0,
    2000,
    0,
    500.0,
    'INR',
    'advanced',
    '["Complete 100km in one day", "Join the Century Club", "Push your limits"]'::jsonb,
    '["Century Club badge", "Digital finisher certificate", "Exclusive jersey (top 100)"]'::jsonb,
    E'Must complete 100km within 24 hours\nActivity must be GPS tracked\nSafety gear mandatory',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '5K for Beginners',
    '5k-for-beginners',
    'Never run before? Start here! An 8-week program designed to take you from couch to running 5km.',
    'running',
    'registration_open',
    CURRENT_DATE + INTERVAL '3 days',
    CURRENT_DATE + INTERVAL '59 days',
    'Virtual - Anywhere',
    5.0,
    1500,
    0,
    0.0,
    'INR',
    'beginner',
    '["Run 5km continuously", "Build fitness foundation", "Enjoy running"]'::jsonb,
    '["5K Finisher badge", "Training guide", "Community support"]'::jsonb,
    E'Follow the couch-to-5k program\nProgress at your own pace\nLog all activities',
    true,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Delhi 10K Trail Run',
    'delhi-10k-trail-run',
    'Experience the beauty of Delhi Ridge on this scenic 10km trail run. Mix of terrain and challenge.',
    'running',
    'registration_open',
    CURRENT_DATE + INTERVAL '21 days',
    CURRENT_DATE + INTERVAL '21 days',
    'Delhi Ridge, New Delhi',
    10.0,
    300,
    0,
    800.0,
    'INR',
    'intermediate',
    '["Complete the trail run", "Experience nature", "Challenge yourself on varied terrain"]'::jsonb,
    '["Finisher medal", "Event t-shirt", "Refreshments and breakfast"]'::jsonb,
    E'Trail running shoes recommended\nCarry water bottle\nFollow trail markers',
    false,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Ultimate Fitness Challenge',
    'ultimate-fitness-challenge',
    'A 6-week multi-sport challenge combining running, cycling, and strength training. For the serious fitness enthusiast.',
    'mixed',
    'registration_open',
    CURRENT_DATE + INTERVAL '10 days',
    CURRENT_DATE + INTERVAL '52 days',
    'Virtual - Anywhere',
    200.0,
    500,
    0,
    2000.0,
    'INR',
    'advanced',
    '["Complete 100km running", "Complete 100km cycling", "30 strength sessions"]'::jsonb,
    '["Ultimate Fitness badge", "Personalized report", "Premium finisher kit"]'::jsonb,
    E'Must complete all three disciplines\nLog all activities with proof\nMinimum weekly targets must be met',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Bangalore Night Riders - 50K',
    'bangalore-night-riders-50k',
    'Join us for a thrilling 50km night cycling event through Bangalore''s illuminated streets. Starts at 9 PM!',
    'cycling',
    'registration_open',
    CURRENT_DATE + INTERVAL '28 days',
    CURRENT_DATE + INTERVAL '28 days',
    'Bangalore, Karnataka',
    50.0,
    400,
    0,
    600.0,
    'INR',
    'intermediate',
    '["Complete 50km night ride", "Experience Bangalore by night", "Group cycling fun"]'::jsonb,
    '["Night Rider badge", "Event jersey", "Midnight refreshments"]'::jsonb,
    E'Working lights on bike mandatory\nReflective gear required\nStay with the group',
    false,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '21-Day Yoga & Run Combo',
    '21-day-yoga-run-combo',
    'Perfect balance of flexibility and endurance. Combine daily yoga sessions with progressive running for holistic fitness.',
    'mixed',
    'registration_open',
    CURRENT_DATE + INTERVAL '5 days',
    CURRENT_DATE + INTERVAL '26 days',
    'Virtual - Anywhere',
    42.0,
    800,
    0,
    500.0,
    'INR',
    'beginner',
    '["Practice yoga daily", "Run 2km daily", "Build mind-body connection"]'::jsonb,
    '["Wellness Warrior badge", "Yoga video library access", "Nutrition guide"]'::jsonb,
    E'Complete both yoga and run each day\nMinimum 20 minutes yoga\nLog all activities',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (slug) DO NOTHING;

-- Show the result
SELECT COUNT(*) as total_events FROM events;
SELECT name, event_type, difficulty_level, is_featured FROM events ORDER BY created_at DESC LIMIT 10;
